
package com.birst;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * A webservice which performs provisioning and execution for Birst
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CommandWebService", targetNamespace = "http://www.birst.com/", wsdlLocation = "file:/E:/generated/commandwebservice.wsdl")
public class CommandWebService
    extends Service
{

    private final static URL COMMANDWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMMANDWEBSERVICE_EXCEPTION;
    private final static QName COMMANDWEBSERVICE_QNAME = new QName("http://www.birst.com/", "CommandWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/generated/commandwebservice.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMMANDWEBSERVICE_WSDL_LOCATION = url;
        COMMANDWEBSERVICE_EXCEPTION = e;
    }

    public CommandWebService() {
        super(__getWsdlLocation(), COMMANDWEBSERVICE_QNAME);
    }

    public CommandWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMANDWEBSERVICE_QNAME, features);
    }

    public CommandWebService(URL wsdlLocation) {
        super(wsdlLocation, COMMANDWEBSERVICE_QNAME);
    }

    public CommandWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMANDWEBSERVICE_QNAME, features);
    }

    public CommandWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommandWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommandWebServiceSoap
     */
    @WebEndpoint(name = "CommandWebServiceSoap")
    public CommandWebServiceSoap getCommandWebServiceSoap() {
        return super.getPort(new QName("http://www.birst.com/", "CommandWebServiceSoap"), CommandWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommandWebServiceSoap
     */
    @WebEndpoint(name = "CommandWebServiceSoap")
    public CommandWebServiceSoap getCommandWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.birst.com/", "CommandWebServiceSoap"), CommandWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMANDWEBSERVICE_EXCEPTION!= null) {
            throw COMMANDWEBSERVICE_EXCEPTION;
        }
        return COMMANDWEBSERVICE_WSDL_LOCATION;
    }

}
